name: publish

on:
  push:
    branches:
      - 'releases/**'
  pull_request:
    branches:
      - 'release/**'
      - 'main'
      - 'master'
    types: [closed]
jobs:

  npm-ci:
    name: npm ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci

  linter:
    needs:
      - npm-ci
    name: linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org'
      - run: npm run lint

  tests:
    needs:
      - npm-ci
    name: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org'
      - run: npm run test

  npm-build-release:
    needs:
      - npm-ci
      - linter
      - tests
    name: npm / github release build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org'
      - run: npm run build

  weapp-build-release:
    needs:
      - npm-ci
      - linter
      - tests
    name: weapp release build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org'
      - run: npx taro build --type weapp

  npm-publish-release:
    needs:
      - npm-ci
      - linter
      - tests
      - npm-build-release
    name: npm / github releases publish
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      NPM_USERNAME: ${{ secrets.NPM_USERNAME }}
      NPM_PASSWORD: ${{ secrets.NPM_PASSWORD }}
      NPM_EMAIL: ${{ secrets.NPM_EMAIL }}
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org'
      - run: npm config set @aries-hui:registry https://registry.npmjs.org
      - run: npm config set //registry.npmjs.org/:_authToken ${{ secrets.NPM_TOKEN }}
      - run: npm run semantic-release

  weapp-publish-release:
    needs:
      - npm-ci
      - linter
      - tests
      - weapp-build-release
    name: weapp release publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org'
      - run: npm run upload:weapp
