name: publish

on:
  push:
    branches:
      - 'releases/**'
  pull_request:
    branches:
      - 'release/**'
      - 'main'
      - 'master'
    types: [closed]
jobs:
  publish:
    name: publish
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [ 16.x ]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      - name: Setup Node ${{ matrix.node_version }}
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org'
      - name: linter
        run:  npm ci
          npm run lint
#      - name: tests
#        run: npm ci
#          npm run test
#      - name: liui build
#        run: npm run build
#      - name: semantic-release
#        run: |
#          npm config set @aries-hui:registry https://registry.npmjs.org
#          npm config set //registry.npmjs.org/:_authToken ${{ secrets.NPM_TOKEN }}
#          npm config list
#          npm run semantic-release
#        env:
#          GH_TOKEN: ${{ secrets.GH_TOKEN }}
#          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
#          NPM_USERNAME: ${{ secrets.NPM_USERNAME }}
#          NPM_PASSWORD: ${{ secrets.NPM_PASSWORD }}
#          NPM_EMAIL: ${{ secrets.NPM_EMAIL }}
      - name: upload wechat
        run: npx taro build --type weapp
          npm run upload:weapp
